name = "main"

[people]
leads = [
    "fslongjin",
    "Chiichen",
    "GnoCiYeH",
    "val213",
    "xiaolin2004",

]

members = [
    "fslongjin",
    "Jomocool",
    "xiaolin2004",
    "1037827920",
    "val213",
    "TTaq",
    "Samuka007",
    "kkkkkong",
    "laokengwt",
    "Chiichen",
    "GnoCiYeH",
    "Samuka007"
]

# 标记已经退休的人
alumni = []

[permissions]

[[github]]
orgs = ["DragonOS-Community"]
